spring:
  application:
    name: client-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    discovery:
      enabled: true
    

eureka:
  instance:
    prefer-ip-address: true

rsa:
  public-key: certs/public.pem